import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <nav style={{
          position: 'sticky',
          top: 0,
          zIndex: 100,
          background: 'rgba(15, 23, 42, 0.8)',
          backdropFilter: 'blur(12px)',
          borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
          padding: '1rem 2rem',
          display: 'flex',
          justifyContent: 'center',
          gap: '2rem'
        }}>
          <Link href="/" style={{ color: '#fff', textDecoration: 'none', fontSize: '1.1rem', fontWeight: 600, padding: '0.5rem 1rem', borderRadius: '8px', transition: 'all 0.2s' }}>
            🌍 매크로 ETF 대시보드
          </Link>
          <Link href="/company" style={{ color: '#fff', textDecoration: 'none', fontSize: '1.1rem', fontWeight: 600, padding: '0.5rem 1rem', borderRadius: '8px', transition: 'all 0.2s' }}>
            🔍 개별 기업 딥다이브
          </Link>
          <Link href="/ib-briefing" style={{ color: '#fff', textDecoration: 'none', fontSize: '1.1rem', fontWeight: 600, padding: '0.5rem 1rem', borderRadius: '8px', transition: 'all 0.2s' }}>
            📰 글로벌 IB 브리핑
          </Link>
          <Link href="/archive" style={{ color: '#fff', textDecoration: 'none', fontSize: '1.1rem', fontWeight: 600, padding: '0.5rem 1rem', borderRadius: '8px', transition: 'all 0.2s' }}>
            📂 과거 아카이브
          </Link>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
